export enum Resource {
  ACCOUNT = 'ACCOUNT',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  CAMPUS = 'CAMPUS',
  AREA = 'AREA',
  BUILDING = 'BUILDING',
  ZONE = 'ZONE',
  ASSET_CATEGORY = 'ASSET_CATEGORY',
  ASSET_TYPE = 'ASSET_TYPE',
  ASSET = 'ASSET',
}
